---

- name: Ensure mandatory base apt packages are installed
  become: true
  no_log: true
  ansible.builtin.apt:
    name:
      - sudo
      - ca-certificates
      - wget
      - curl
      - cmatrix
      - nano
      - htop
      - xclip
    state: present
    update_cache: yes
    cache_valid_time: 3600
